version: '3.8'

services:

  mongo:
    image: mongo:7.0
    container_name: citas_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: citas_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: citas_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - medicos-service
      - citas-service

  auth-service:
    build: ./auth-service
    image: auth:1.0
    container_name: auth_service
    ports:
      - "3001:3001"
    env_file:
      - ./auth-service/.env
    environment:
      - LARAVEL_API=http://host.docker.internal:8000
    restart: unless-stopped

  medicos-service:
    build: ./medicos-service
    image: medicos:1.0
    container_name: medicos_service
    ports:
      - "3002:3002"
    env_file:
      - ./medicos-service/.env
    environment:
      - LARAVEL_API=http://host.docker.internal:8000
    restart: unless-stopped

  citas-service:
    build: ./citas-service
    image: citas:1.0
    container_name: citas_service
    ports:
      - "3003:3003"
    env_file:
      - ./citas-service/.env
    environment:
      - MONGODB_HOST=mongo
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local
